import crypto from 'crypto';
import fs from 'fs';
const sec = fs.readFileSync(new URL('../.env', import.meta.url), 'utf8').match(/^PAYSTACK_SECRET_KEY=(.+)$/m)[1].trim();
const body = JSON.stringify({ event: 'charge.success', data: { reference: 'WH-TEST-1', metadata: { group_id: 'g-aj4821', membership_id: 'm-bola', cycle_id: 'c-aj4821-1', pot: 5000, fee: 75 } } });
const sig = crypto.createHmac('sha512', sec).update(body).digest('hex');
const good = await fetch('http://localhost:4000/webhooks/paystack', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-paystack-signature': sig }, body });
console.log('GOOD-SIG:', await good.text());
const bad = await fetch('http://localhost:4000/webhooks/paystack', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-paystack-signature': 'nope' }, body });
console.log('BAD-SIG:', bad.status, await bad.text());
const banks = await fetch('http://localhost:4000/api/banks').then((r) => r.json());
console.log('BANKS:', Array.isArray(banks) ? `${banks.length} banks, e.g. ${banks.slice(0, 3).map((b) => b.code).join(',')}` : JSON.stringify(banks).slice(0, 100));
